### ISSUE TITLE
Video element size changes sometimes

### ISSUE THREAD

**Issue by PHPGuus** [eyeson-team/react-web-gui-example#11]
Hi there,

sometimes the sizing of the <video> element is changing. Is there anyways that this can be prevented, either in JS or in HTML by some clever boxing? This happens sometimes in a one-to-one conference, but also we've seen it happen when there is a steady number of people in the conference, so there seemingly no reason for the <video> element size to change all of a sudden...

Have you seen this in the past, and how can it be prevented, please?

Thank you and best regards,
Guus

**Comment by unused** [comment]
Hi, if the stream is kept in a HTML video element you can apply any common styles. For sure setting up sizing limits is required especially for screen sharing as the video ration will differ. If you have troubles keeping the video element in place you can join a meeting using the provided eyeson GUI and have a look on the CSS rules applied there. The difference for one-to-one to more participants is likely caused by [using sfu mode](https://eyeson-team.github.io/api/api-reference/#eyeson-room) which can be configured using the `options[sfu_mode]` parameter. Best wishes!

**Comment by PHPGuus** [comment]
Hi, could the documentation explain the possible values of SFU mode, please, or is this common knowledge that I can lookup elsewhere?

**Comment by unused** [comment]
Thank you for the feedback, I'll add some details to this section. When using eyeson you will have a [single media stream](https://help.eyeson.team/eyeson-room/en/articles/735255-what-is-single-stream-technology) received managed by the MCU. This however results in having two participants showing up in a single video, as everyone sees exactly the same video. However we do offer a SFU (selective forwarding unit) mode [for two people](https://help.eyeson.team/eyeson-room/en/articles/1330787-how-is-the-video-conversation-synchronized-with-video-and-audio) so you can show the local stream as well as the remote stream. This mode is available while having two participants (peer-to-peer, `ptp`) or while sharing the screen (`screencast`) and it can be completely `disabled`.
