### ISSUE TITLE
Want to change domain 

### ISSUE THREAD

**Issue by Dhananjay03121997** [eyeson-team/react-web-gui-example#34]
Can you help me in changing the domain name of the video call in the guest link in node js?

**Comment by unused** [comment]
I'm sorry to say but there seems some basic misunderstanding. I guess you just want to have eyeson meetings to appear within your domains. As stated in #32 you can easily use a custom UI which is also not dependent on any framework, so you can even use static HTML to do so. In order to get an idea of how to work with the eyeson API I'd ask you to revisit the [overview](https://accounts.eyeson.team/developer) and [documentation](https://eyeson-team.github.io/api/).
