### ISSUE TITLE
API guest create can return error 500

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#52]
I was inside of our custom videoroom and started a guest create. Before that I switched browser and maybe closed the old Tab in Chrome before continuing on Safari.

It returned me an error 500.

<img width="821" alt="Screenshot 2022-04-27 at 01 38 28" src="https://user-images.githubusercontent.com/10122382/165409936-999b4c3c-8440-4ee0-a81a-6ad24f9ca50b.png">

I thought maybe the token was expired and tested it but seems your API tells with status 410 if that token is expired:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/10122382/165410257-2e5d784b-ade9-499a-ac8b-7d6268d1351d.png">

I now know exactly what happened on our side and have a UnitTest for that Scenario and a Custom ErrorMessage. But how should I handle this error? How can I be in a room and not have the room?

Sentry tells me that this happened before so not a one-time occurance.

As far as I know you close the room after last person leaves. Can I revive the very same room somehow? If you don't have that PLEAAAASE add this. It is late right now but I cannot think of another fix than recreating the room and all the guests. Recreating a room just because someone clicks on add guest does not sound like a good solution.

**Comment by codingyourlife** [comment]
timestamp: 2022-04-26T21:00:43.585305Z
I send you the sentry json event export via email to eyeson support.

If I'd need to guess I was trying to add a guest to a room that was shutting down.

**So simple usecase that makes the problem scenario obvious:**
When I am the only one in the room and I want to switch browser I close Chrome (-> here sadly the eyeson room closes on your side and very very sadly also the tokens expire if I'm not mistaken), open Firefox and join again (-> here I check on the backend that the room is no longer valid because I receive 410 and create another including adding all guests so I basically have all new tokens).

So one thing that would already mitigate the problem a lot is if the room would stay open a minimum time of 10 minutes. That's enough time for browser switching etc.

And being able to revive the token (mabye via a separate revive key) for I don't know a month or a year it would in my opinion fully solve the problem. That when I try to access a gone room it's imply not gone but revived.

We right now do some trickery and check if the room is still there and otherwise just handle the situation and recreate the previous requests and use the new tokens. So it's a clone of everything including room and guests. It works but there are edgecases where it does not work perfectly. Also adding guests can take a while (we do it asynchronously).

**Comment by unused** [comment]
The timeout that automatically initiates the shutdown of a meeting. This takes already several minutes. Its unlikely that you cannot switch browsers in between. However it seems the problem is with the guest token. The guest token is used to invite users during a meeting without requiring to authenticate again, in other words: the authorized users (via access key) is able to invite new users on-the-fly. In case you create new users with the guest token, this is the wrong way to go. Creating new (regular) users will always ensure there is a video conference ready for you.

Thank you for the hint, that creating a guest for a shutting-down conference might cause a status code 500 error. We will check this, however the outcome of a solution to this will only be a change to a proper 4xx status, as no guests should be available for an inactive meeting (w/o active participants).

Please do not hesitate to leave a reply if you have any further questions.
