### ISSUE TITLE
INVALID_STATE_ERROR - Invalid status: CANCELED in sip.js

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#53]
This was a room where some people could join and one could not join

![image](https://user-images.githubusercontent.com/10122382/165413059-09a72f79-e24e-4f19-bad2-b45b7c5f5b5e.png)

Any advice? What does that mean and what happened here?

**Comment by opusonline** [comment]
Hi.

This error comes from the sip library and is raised whenever the sip session was already closed, but still wanted to send a message in that session. This is nothing to worry about since the session was already closed, so the call has ended.

You may want to use the latest release v1.8.0 of eyeson-js (https://www.npmjs.com/package/eyeson) where we've removed the sip library.

Please do not hesitate to leave a comment if you need any further help!
Best regards
