### ISSUE TITLE
Issue with muted microphone while screen sharing.

### ISSUE THREAD

**Issue by natschz** [eyeson-team/react-web-gui-example#55]
So there is an issue, when sharing the screen, where the muted microphone is ignored and then afterwards it isn't possible to mute it again.

**Comment by unused** [comment]
Thank you for the input, unfortunately we cannot reproduce any issue with muting the microphone during screenshare in our default web ui - can you please provide a short description on which steps to take to end up with a unmutable microphone such that our QA team can check the problem. If you don't mind it would be great if you could share your browser and operating system (incl. version used).

**Comment by natschz** [comment]
So I have to PC's (one of them without a cam).

I'm openening starting to screen share on the PC with the cam, when I'm muted before screen sharing I can't unmuted and vice versa.

After closing the stream it seams like  a few seconds it starts to work again.

Also it's kind of weird if you have no cam on one machine the last image of the screen share seems to get stuck there. Also if you have no cam I'm kind of missing the "no cam" icon for this users, it shows just a blank screen for it.

**Comment by btreuer** [comment]
Thank you for the information. 
Regarding the short delay leaving the presentation mode, it is because the full-screen presentation is done in sfu-mode, the meetings in mcu-mode. Switching between these two modes can cause some delay depending partly on the participants' hard/software.
Participants with muted cams or w/o cams are not shown in mcu-mode, not even with a symbol.
We could not reproduce your mic mute/unmute issue. Can you provide us with more details? I did a test on Win11 with latest Chrome, Firefox and Edge.
OS & version: 
browser & version:
