### ISSUE TITLE
Eyeson.start() results in 404 on Storybook Testing

### ISSUE THREAD

**Issue by Alan-Qiao** [eyeson-team/react-web-gui-example#58]
I am building a component based on this example, but I ran into trouble while trying to test this with storybook.

It seems that eyeson.start() attempts to access the url "http://localhost:6006/BlouCpJnyIhWDwteO6mYyS4iIOV8scGsxtE3dDYZ7S/rooms/LF21kzcFhiX1sBUDJ26BOWO5" in establishing a connection to the created meeting room. (My storybook port is configured to 6006) This results in 404 and so the video stream does not load. 

Any ideas what this url means and why this may be the case?

**Comment by unused** [comment]
This URL looks weird to me as well. However please note that if you use the eyeson service in a component library like storybook you'll need to start a full video conference every time you visit your dependent components. This will also count against [your service usage](https://help.eyeson.com/api-pricing-guide). Instead you might just want to handle the states and keep business logic on a higher level. Considering a view component for the video part you can show a local camera stream or a captured video stream from a hidden video element instead. Let me know if you have any further questions. In case you want to figure out more about the URL I need to ask for more details, e.g. a code snippet such that I can reproduce this problem.

**Comment by Alan-Qiao** [comment]
I put together the following simple repo adapted from your react example which mocks my use case. (Didn't do styling yet)

https://github.com/Alan-Qiao/eyeson-test-frame

I abandoned the storybook testing for now, but I am still running into the same url issue when I attempt to start a meeting normally. In the attached repo, steps to reproduce the error is as follows:
1. npm run start
2. input a string for player name and a string for room name
3. click submit

This time, the console log shows a "websocket" undefined error, but in tracking the network requests it seems that eyeson.js is making a get request to a url of the form "http://localhost:3000/BlouCpJnyIhWDwteO6mYyS4iIOV8scGsxtE3dDYZ7S/rooms/{valid access key}"

**Comment by unused** [comment]
There are several issues with your code, some troubles are caused by multiple calls of same handler functions, you'll have to revisit the [React documentation](https://reactjs.org/docs/hooks-intro.html) as we cannot provide support for this. For the eyeson part there are two crucial things to fix: First of all you should never expose your secret(!) API key. That for please remove it from your public GitHub repository (config) and [regenerate it](https://help.eyeson.com/overview-developer-portal) to avoid misuse. Additionally it should not be exposed in your (web) application, so you need to handle that communication server-side and just forward the access-key to your client. The second issue - the one that produces the strange URL - is caused by some override of the configuration. You can simply [remove the line](https://github.com/Alan-Qiao/eyeson-test-frame/blob/main/src/VideoCall.jsx#L65) `eyeson.config.api = conf.APIKEY` in your video call component. Let me know if you have any further questions!
