### ISSUE TITLE
Cannot read properties of null (reading 'sdp')

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#66]
![image](https://github.com/eyeson-team/react-web-gui-example/assets/10122382/7576f471-ccc1-4b69-9116-9b1bbd5d16f8)

we use version 1.8.4
implications unknown

**Comment by opusonline** [comment]
Hi. Thanks for your feedback!

We don't see this error in our default UI, so I have to ask some questions.

Is this happening every time, so that no meeting is working?
Are there special circumstances when this is happening?
Is it browser-specific, like it is only happening in one specific browser, but works in other browsers?
Is it related to specific participant and works for others?
The latest version of eyeson-js is 1.8.8 (https://www.npmjs.com/package/eyeson?activeTab=versions). Please try with a newer version to check if the error is resolved.

Best regards,
Stefan

**Comment by opusonline** [comment]
This issue was closed due to lack of activity for past 5 days.

Please do not hesitate to leave a comment if you need any further help!

Best regards
