### ISSUE TITLE
Bug: Sending start_stream with virtualBackground "off" shows black background instead of none

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#70]
Here how I temporary fixed it:
<img width="1221" alt="image" src="https://github.com/eyeson-team/react-web-gui-example/assets/10122382/053ca116-0283-49d0-88c7-a4b6066abb73">

Note: selectedVirtualBackground or DeviceManager.getStoredVirtualBackgroundType() made no difference here.

**Comment by opusonline** [comment]
Hello @codingyourlife,

The `start_stream` event is meant to enable or disable each feature, like audio, video, screen, and also virtualBackground. So they are all of type boolean. See https://docs.eyeson.com/docs/js/events/stream#start_stream

It works in 2 stages. In the first stage, DeviceManager is used to make selections for each feature like microphone device for audio, camera device for video, and virtual background type for virtual background, and then store all selections with `deviceManager.storeConstraints()`.
In stage 2. each feature is either enabled or disabled, and if enabled it is started with the previous stored selection.

Just as an example, calling `start_stream` with virtualBackground: "off" is failing the same way as using video: "Logitech WebCam abc" would fail, because those are 2 different stages. One to setup and one to apply.

I have added a new section to Eyeson-JS documentation to make it a bit more clear:
https://docs.eyeson.com/docs/js/utilities/devicemanager#virtual-background

I order to disable virtual background, you need to send `start_stream` with virtualBackground set to false. No matter which type is stored in the setup.

I hope this helps for now.

Please do not hesitate to leave a reply if you have any further questions.

Best regards
